"use client"

import { useState } from "react"
import { motion, AnimatePresence } from "framer-motion"
import { Plus, Minus } from "lucide-react"

const faqs = [
  {
    question: "How does QuizNova AI generate questions?",
    answer: "QuizNova AI uses advanced large language models to analyze your topic or uploaded documents. It identifies key concepts, facts, and relationships to generate contextually accurate questions. The AI is trained on millions of educational materials to ensure questions are pedagogically sound and appropriate for different learning levels."
  },
  {
    question: "What types of questions can I create?",
    answer: "You can create multiple choice questions (MCQs), true/false questions, fill-in-the-blank, short answer, matching questions, and essay prompts. Our Pro plan includes advanced question types like case studies, scenario-based questions, and image-based assessments."
  },
  {
    question: "Can I upload my own teaching materials?",
    answer: "Yes! QuizNova AI supports PDF, Word documents, PowerPoint presentations, and even images of textbook pages. Our AI will analyze the content and generate relevant questions based on the material, saving you hours of manual work."
  },
  {
    question: "Is the content generated by AI accurate?",
    answer: "QuizNova AI is designed to generate high-quality and contextually relevant questions using advanced AI models. However, we always recommend reviewing generated content before using it in exams or classrooms. You can easily edit questions, answers, and explanations directly in the editor."
  },
  {
  question: "Can I generate quizzes from PDFs?",
  answer: "Yes! You can upload PDFs and generate AI-powered MCQs, quizzes, and exams instantly from your study material or notes."
},
  {
    question: "What subjects and grade levels does QuizNova support?",
    answer: "QuizNova AI works across all subjects—from STEM to humanities, languages to arts. It supports content from elementary school through graduate level. The AI automatically adjusts question complexity based on your specified grade level or difficulty setting."
  },
  {
    question: "Is my content and student data secure?",
    answer: "We prioritize user privacy and take reasonable measures to protect uploaded content and generated quizzes. We are continuously improving our security and data protection systems."
  },
  {
    question: "Can I try QuizNova before purchasing?",
    answer:  "Yes! Our Free plan allows users to generate quizzes and explore core features before upgrading to a premium plan."
  }
]

export function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(0)

  return (
    <section id="faq" className="py-24 lg:py-32 relative">
      <div className="container mx-auto px-4">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center max-w-3xl mx-auto mb-16"
        >
          <span className="text-primary font-medium text-sm uppercase tracking-wider">FAQ</span>
          <h2 className="text-3xl lg:text-5xl font-bold mt-4 mb-6 text-balance">
            Frequently asked questions
          </h2>
          <p className="text-muted-foreground text-lg text-pretty">
            Everything you need to know about QuizNova AI. Can&apos;t find what you&apos;re looking for? Contact our support team.
          </p>
        </motion.div>

        {/* FAQ Items */}
        <div className="max-w-3xl mx-auto space-y-4">
          {faqs.map((faq, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: index * 0.05 }}
              className="rounded-xl border border-border bg-card/50 backdrop-blur-sm overflow-hidden"
            >
              <button
                onClick={() => setOpenIndex(openIndex === index ? null : index)}
                className="w-full flex items-center justify-between p-6 text-left hover:bg-secondary/30 transition-colors"
              >
                <span className="font-medium pr-4">{faq.question}</span>
                <span className="flex-shrink-0 w-8 h-8 rounded-full bg-secondary flex items-center justify-center">
                  {openIndex === index ? (
                    <Minus className="h-4 w-4" />
                  ) : (
                    <Plus className="h-4 w-4" />
                  )}
                </span>
              </button>
              <AnimatePresence>
                {openIndex === index && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.2 }}
                    className="overflow-hidden"
                  >
                    <p className="px-6 pb-6 text-muted-foreground leading-relaxed">
                      {faq.answer}
                    </p>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  )
}
